CREATE TABLE [dbo].[MyTable]
(
    -- TODO: Add [PartitionKey]
    [RowKey] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID()
    ,[Timestamp] DATETIME NOT NULL DEFAULT GETUTCDATE()
    ,[MyInput] BIT NOT NULL
);
